### ISSUE TITLE
TypeError in cpylog killing import of pyNastran

### ISSUE THREAD

**Issue by jdeaton** [SteveDoyle2/cpylog#2]
I have wrapped some parts of pyNastran in Cython and use it to read in basic Nastran mesh information in our MAST C++ FEA tool (https://github.com/MASTmultiphysics/mast-multiphysics). 

I've encountered an issue in cpylog when its imported by pyNastran on both macOS and Ubuntu.

This looks to be some sort of checking on the shell session type and there is a case to be  handled when `get_default_session()` returns None possibly? Should it return an empty list rather than None in some cases?

Below is a snippet of the Python TypeError output from our CI. I'm installing both pyNastran and cpylog via pip in Python 3.7. I was able to bypass the error by commenting out the entire section containing line 44 in __init__.py.

```
1:   File "/usr/local/lib/python3.6/dist-packages/pyNastran/bdf/bdf.py", line 23, in <module>
1:     from cpylog import get_logger2
1:   File "/usr/local/lib/python3.6/dist-packages/cpylog/__init__.py", line 44, in <module>
1:     if session_name and 'powershell.exe' in session_name or 'cmd.exe' in session_name:
1: TypeError: argument of type 'NoneType' is not iterable
```

**Comment by jdeaton** [comment]
On closer look, it seems you must have been hitting this same issue as you commented this offending code out in your `master` branch after v1.1 it looks like. Do you think you could cut a new release on PyPI?

**Comment by SteveDoyle2** [comment]
Sure.  I've pushed a new version.

Glad you're using it in MAST!
